version: "3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
    links:
      - teamcity-agent
      - teamcity-minimal-agent
    restart: always
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=regular_agent
      - DOCKER_IN_DOCKER=start
    volumes:
      - ./teamcityagent.conf:/data/teamcity_agent/conf
      - ./docker_volumes:/var/lib/docker
    privileged: true
    restart: always
  teamcity-minimal-agent:
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=minimal_agent
    restart: always
    volumes:
      - ./teamcityminimalagent.conf:/data/teamcity_agent/conf
      - ./docker_volumes:/var/lib/docker